# Generated by Django 2.2.5 on 2021-05-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favlist',
            options={},
        ),
    ]
