# Generated by Django 2.2.5 on 2021-04-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cast', models.ManyToManyField(blank=True, related_name='Actors', to='people.Person')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='categories.Category')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Derector', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
